
$(BIN)/jlucidity/source/reflect/ReflectionClassSource.class:	$(SRC)/jlucidity/source/reflect/ReflectionClassSource.java $(BIN)/jlucidity/source/ClassSource.class $(BIN)/jlucidity/misc/IOUtils.class

$(BIN)/jlucidity/source/reflect/ReflectionClassInfo.class:		$(SRC)/jlucidity/source/reflect/ReflectionClassInfo.java $(BIN)/jlucidity/info/ClassInfo.class \
						$(BIN)/jlucidity/source/reflect/ReflectionConstructorInfo.class \
						$(BIN)/jlucidity/source/reflect/ReflectionFieldInfo.class \
						$(BIN)/jlucidity/source/reflect/ReflectionMethodInfo.class
$(BIN)/jlucidity/source/reflect/ReflectionConstructorInfo.class:	$(SRC)/jlucidity/source/reflect/ReflectionConstructorInfo.java $(BIN)/jlucidity/info/ConstructorInfo.class
$(BIN)/jlucidity/source/reflect/ReflectionFieldInfo.class:		$(SRC)/jlucidity/source/reflect/ReflectionFieldInfo.java $(BIN)/jlucidity/info/FieldInfo.class
$(BIN)/jlucidity/source/reflect/ReflectionMethodInfo.class:	$(SRC)/jlucidity/source/reflect/ReflectionMethodInfo.java $(BIN)/jlucidity/info/MethodInfo.class
