$(BIN)/jlucidity/filter/ClassSearchFilter.class:		$(SRC)/jlucidity/filter/ClassSearchFilter.java
$(BIN)/jlucidity/filter/DirectoryFilter.class:		$(SRC)/jlucidity/filter/DirectoryFilter.java



$(BIN)/jlucidity/filter/ClassSearchFilter.class:		$(SRC)/jlucidity/filter/ClassSearchFilter.java
$(BIN)/jlucidity/filter/DirectoryFilter.class:		$(SRC)/jlucidity/filter/DirectoryFilter.java
