$(BIN)/jlucidity/env/GlobalClassList.class:			$(SRC)/jlucidity/env/GlobalClassList.java $(BIN)/jlucidity/source/ClassSource.class \
						$(BIN)/jlucidity/info/PackageInfo.class $(BIN)/jlucidity/info/ClassInfo.class
$(BIN)/jlucidity/env/ClassPath.class:	$(SRC)/jlucidity/env/ClassPath.java
