# Hmph, this would be great...if it worked.
#.SECONDARYEXPANSION:

.PHONY:		cleansrc
cleansrc:
	@$(RM) $(CFG)/JARCSCIRCDEP $(CFG)/SOURCECIRCDEP $(CFG)/BCCFG

include $(SRC)/jlucidity/Makefile
include $(SRC)/jlucidity/misc/Makefile
include $(SRC)/jlucidity/lang/Makefile
include $(SRC)/jlucidity/info/Makefile
include $(SRC)/jlucidity/source/Makefile
include $(SRC)/jlucidity/env/Makefile
include $(SRC)/jlucidity/filter/Makefile
include $(SRC)/jlucidity/bytecode/Makefile
include $(SRC)/jlucidity/test/Makefile
